### ISSUE TITLE
Font awesome 

### ISSUE THREAD

**Issue by oliverjessner** [oliverjessner/browsersize.app#17]
Due to some user research and common sense, the click event on main has not a good 
UX. 

- serve font awesome via server
- add https://fontawesome.com/icons/computer-mouse?f=classic&s=solid next to viewport/resolution

**Comment by oliverjessner** [comment]
The SVG should be a background image element so you can change it via CSS

```css
.cursor {
    background-image: url(assets/fontawesome/mouse.svg);
    height: 32px;
    width: 32px;
    background-repeat: no-repeat;
}
```

```css
.indicator:hover .cursor {
    background-image: url('assets/fontawesome/mouse-hover.svg');
}
```

better way to change an image
